import ReactQueryProvider from "@/components/providers/react-query-provider";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { Navbar } from "@/components/ui/navbar";
import { Footer } from "@/components/ui/footer";
import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${GeistSans.variable}`}
      suppressHydrationWarning
    >
      <body className="bg-white dark:bg-black">
        <ThemeProvider>
          <Navbar />
          <Toaster richColors />
          <ReactQueryProvider>
            <main className="mx-auto min-h-screen max-w-7xl px-4 pt-16 sm:px-6 lg:px-0">
              {children}
            </main>
          </ReactQueryProvider>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
